const data = [
  {
    thumbnail: 'https://www.freeiconspng.com/uploads/no-image-icon-4.png',
    variants: [],
    name: 'Kiwis',
    desc: 'Fresh chilean kiwis',
    listed: 'true',
    price: '9.99',
    inStock: 'true',
  },
  {
    thumbnail: 'https://www.freeiconspng.com/uploads/no-image-icon-4.png',
    variants: [],
    name: 'Strawberries',
    desc: 'Farm fresh. Local when available',
    listed: 'true',
    price: '6.99',
    inStock: 'true',
  },
  {
    thumbnail: 'https://www.freeiconspng.com/uploads/no-image-icon-4.png',
    variants: [],
    name: 'Blueberries',
    desc: 'Blueberries are a delicious snack for the entire family, any time of day. Enjoy them sprinkled over cereal, oatmeal or granola as part of a healthy breakfast. ',
    listed: 'true',
    price: '9.99',
    inStock: 'true',
  },
  {
    thumbnail: 'https://www.freeiconspng.com/uploads/no-image-icon-4.png',
    variants: [],
    name: 'Cherries',
    desc: 'These cherries are a good source of dietary fiber',
    listed: 'true',
    price: '9.99',
    inStock: 'true',
  },
  {
    thumbnail: 'https://www.freeiconspng.com/uploads/no-image-icon-4.png',
    variants: [],
    name: 'Tomatoes',
    desc: 'These ripe tomatoes are the perfect ingredient for a variety of tasty dishes. Use them to make a decadent tomato sauce for a pasta dish; try slicing them up and pairing with mozzarella cheese, basil and balsamic vinegar; or simply enjoy them on their own as a nutritious snack.',
    listed: 'true',
    price: '6.99',
    inStock: 'true',
  },
  {
    thumbnail: 'https://www.freeiconspng.com/uploads/no-image-icon-4.png',
    variants: [],
    name: 'Cucumbers',
    desc: 'Organically grown in the richest soil available.',
    listed: 'true',
    price: '3.99',
    inStock: 'true',
  },
  {
    thumbnail: 'https://www.freeiconspng.com/uploads/no-image-icon-4.png',
    variants: [],
    name: 'Rice',
    desc: 'Organically grown in the richest soil available. No pesticides nor herbicides were used in producing these fine grains',
    listed: 'true',
    price: '3.99',
    inStock: 'true',
  },
  {
    thumbnail: 'https://www.freeiconspng.com/uploads/no-image-icon-4.png',
    variants: [],
    name: 'Watermelon',
    desc: 'Organically grown in the richest soil available',
    listed: 'true',
    price: '3.99',
    inStock: 'true',
  },
];
const productVariantsData = [{}];

module.exports = data;
